jobs:
  include:
  - os: windows
    deploy:
    - provider: releases
      skip_cleanup: true
      dpl_version: 2.0.3.beta.4
      on:
        tags: true
os: linux
dist: xenial
language: c
compiler: gcc
