jobs:
  include:
  - dist: xenial
    os: linux
    deploy:
    - provider: releases
      token: "$GITHUB_APIKEY"
      file: "$FILE_NAME"
      skip_cleanup: true
      dpl_version: 1.10.16
      on:
        tags: true
  - dist: bionic
    os: linux
  - os: windows
    deploy:
    - provider: releases
      token: "$GITHUB_APIKEY"
      file: "$FILE_NAME"
      skip_cleanup: true
      dpl_version: 2.0.3.beta.4
      on:
        tags: true
os: linux
dist: xenial
language: c
compiler: gcc
